# Generated by Django 4.2.3 on 2023-07-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_alter_vacancy_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
