# Generated by Django 4.2.3 on 2023-07-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_vacancy_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
